/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package settings.gui;

import java.nio.file.Paths;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import simulator.beans.Kasse;

/**
 *
 * @author Lukas Krobath
 */
public class AddCashpointDlg extends javax.swing.JDialog {

    private DefaultComboBoxModel<Kasse.TYP> dcbm;
    private boolean okay = false;
    private Kasse result;
    private boolean locked;

    /**
     * Creates new form AddCashpointDlg
     *
     * @param parent
     * @param modal
     */
    public AddCashpointDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Kassa hinzufügen");
        setLocationRelativeTo(parent);
        setIconImage(new ImageIcon(Paths.get(System.getProperty("user.dir"), "src", "main", "java", "general", "res", "img", "logo.png").toString()).getImage());
        dcbm = new DefaultComboBoxModel<>();
        dcbm.addElement(Kasse.TYP.RB4);
        dcbm.addElement(Kasse.TYP.RB5);
        dcbm.addElement(Kasse.TYP.RB6);
        cbType.setModel(dcbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfIp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("IP Adresse:");
        getContentPane().add(jLabel1);

        tfIp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfIp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onKeyReleased(evt);
            }
        });
        getContentPane().add(tfIp);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3);

        tfId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onLock(evt);
            }
        });
        getContentPane().add(tfId);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Kassenart:");
        getContentPane().add(jLabel4);

        cbType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(cbType);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Okay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOkay(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    private void onOkay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOkay
        try {
            int id = -1;
            switch ((Kasse.TYP) cbType.getSelectedItem()) {
                case RB4:
                    id = 97;
                    break;
                case RB5:
                    id = 96;
                    break;

                case RB6:
                    id = 120;
                    break;
            }
            
            result = new Kasse(Integer.parseInt(tfId.getText()), id, tfIp.getText(), (Kasse.TYP) cbType.getSelectedItem());
            okay = true;
            dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Fehler beim Hinzufügen einer neuen Kasse!\n"
                    + "Bitte füllen Sie alles aus und geben Sie nur folgende Werte ein:\n- IP Adresse: Schema '#.#.#.#' zum Beispiel '10.0.0.1'\n"
                    + "- ID: Ganzzahl\n- Gruppen ID: Ganzzahl", "Fehler beim Erzeugen einer neuen Kassa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onOkay

    private void onKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyReleased
        if(!locked){
            String[] full = tfIp.getText().split("\\.");
            tfId.setText(full[full.length-1]);
        }
    }//GEN-LAST:event_onKeyReleased

    private void onLock(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onLock
    locked = true;
    }//GEN-LAST:event_onLock

    public boolean isOkay() {
        return okay;
    }

    public Kasse getResult() {
        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCashpointDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCashpointDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCashpointDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCashpointDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCashpointDlg dialog = new AddCashpointDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Kasse.TYP> cbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfIp;
    // End of variables declaration//GEN-END:variables
}
