/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorer.gui;

import dashboard.bl.DatabaseGlobalAccess;
import dashboard.database.DB_Access_Manager;
import explorer.bl.ExplorerTreeModel;
import explorer.io.ExplorerIO;
import general.beans.io_objects.TestCaseRun;
import general.bl.GlobalAccess;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;

/**
 *
 * @author Anna Lechner
 */
public class ExplorerTestcasePanel extends javax.swing.JPanel {

    private TestCaseRun tc;
    private String regEx = "Testcase_[0-9]+ - ";
    private ExplorerTreeModel etm;

    /**
     * Creates new form ExplorerTestcasePanel
     *
     * @param testCase
     * @param etm
     */
    public ExplorerTestcasePanel(TestCaseRun testCase, ExplorerTreeModel etm) {
        initComponents();
        this.tc = testCase;
        this.etm = etm;
        setObjectValuesOnTf();
    }

    /**
     * Method to add all passed object values on the JTextFields
     */
    private void setObjectValuesOnTf() {
        tfTc.setText(tc.getDescription().replaceAll(regEx, ""));
        String shortPath = tc.getPath().toString().substring(tc.getPath().toString().indexOf("projekte\\") + ("projekte\\").length());
        tfTcPath.setText(shortPath);
        tfTcPath.setEditable(false);
        if (tfTc.getText().contains("Init") || tfTc.getText().contains("Cleanup")) {
            tfTc.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paLeft = new javax.swing.JPanel();
        lbTc = new javax.swing.JLabel();
        lbTcPath = new javax.swing.JLabel();
        paRight = new javax.swing.JPanel();
        tfTc = new javax.swing.JTextField();
        tfTcPath = new javax.swing.JTextField();
        paSouth = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        paLeft.setPreferredSize(new java.awt.Dimension(150, 290));
        paLeft.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        lbTc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTc.setText("Testcase:");
        paLeft.add(lbTc);

        lbTcPath.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTcPath.setText("Testcase Path:");
        paLeft.add(lbTcPath);

        add(paLeft, java.awt.BorderLayout.WEST);

        paRight.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        tfTc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paRight.add(tfTc);

        tfTcPath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paRight.add(tfTcPath);

        add(paRight, java.awt.BorderLayout.CENTER);

        paSouth.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        btOk.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOk(evt);
            }
        });
        paSouth.add(btOk);

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btCancel.setText("Änderungen verwerfen");
        btCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 40, 1));
        btCancel.setPreferredSize(new java.awt.Dimension(49, 35));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        paSouth.add(btCancel);

        add(paSouth, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is called when the user clicks on the "Cancel" button
     *
     * @param evt
     */
    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        setObjectValuesOnTf();
    }//GEN-LAST:event_onCancel

    /**
     * Method that is called when the user clicks on the "OK" button
     *
     * @param evt
     */
    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        try {
            if (!tfTc.getText().contains("Init") && !tfTc.getText().contains("Cleanup")) {
                File toBeRenamed = tc.getPath().toFile();
                String newName = tfTc.getText();
                if (newName.trim() != null && !newName.trim().isEmpty()) {
                    String oldTxtDescription = tc.getDescription().replaceAll(regEx, "");
                    String prefix = "";
                    if (!oldTxtDescription.trim().equalsIgnoreCase("Test") || oldTxtDescription.trim().equals("case")) {
                        prefix = tc.getDescription().replaceAll(oldTxtDescription, "");
                    } else {
                        prefix = tc.getDescription().substring(0, tc.getDescription().indexOf("-") + 2);
                    }
                    //change run.xml description
                    String oldDescription = tc.getDescription();
                    tc.setDescription(prefix + newName);
//                    if (GlobalParamter.getInstance().isStatistic_db_reachable()) {
//                        DB_Access.getInstance().updateEntry(tc, oldDescription);
//                        DB_Access.getInstance().addChangeEntry(tc, ChangeType.CHANGED);
//                    }
                    
                    if(DatabaseGlobalAccess.getInstance().isDbReachable()){
                        if(DatabaseGlobalAccess.getInstance().getCurrentNutzer() != null){
                            DB_Access_Manager.getInstance().addChangeEntry(tc, "CHANGED");
                        } else {
                            DB_Access_Manager.getInstance().updateData();
                            JOptionPane.showMessageDialog(GlobalAccess.getInstance().getTest_ide_main_frame(), "Kein Nutzer ausgewählt mit welchem diese Änderung in der Datenbank"
                                    + " assoziert werden kann. Um dies sicherzustellen sollte ein Nutzer in den Einstellungen ausgewählt werden");
                        }
                    }
                    ExplorerIO.changeNodeOfTG(Paths.get(toBeRenamed.toString(), "run.xml"), "description", tc.getDescription());
                    etm.fireTreeStructureChanged();
                }
            }
        } catch (ParserConfigurationException | SAXException | IOException | XPathExpressionException | TransformerException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onOk


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbTc;
    private javax.swing.JLabel lbTcPath;
    private javax.swing.JPanel paLeft;
    private javax.swing.JPanel paRight;
    private javax.swing.JPanel paSouth;
    private javax.swing.JTextField tfTc;
    private javax.swing.JTextField tfTcPath;
    // End of variables declaration//GEN-END:variables
}
