/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorer.gui;

import general.beans.io_objects.ProjectRun;

/**
 *
 * @author Anna Lechner
 */
public class ExplorerProjectPanel extends javax.swing.JPanel {

    private ProjectRun project;
    
    /**
     * Creates new form ExplorerProjectPanel
     * @param project
     */
    public ExplorerProjectPanel(ProjectRun project) {
        initComponents();
        this.project = project;
        tfProjectName.setText(project.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paLeft = new javax.swing.JPanel();
        lbProjectName = new javax.swing.JLabel();
        paRight = new javax.swing.JPanel();
        tfProjectName = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        paLeft.setPreferredSize(new java.awt.Dimension(150, 290));
        paLeft.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        lbProjectName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbProjectName.setText("Projektname:");
        paLeft.add(lbProjectName);

        add(paLeft, java.awt.BorderLayout.WEST);

        paRight.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        tfProjectName.setEditable(false);
        tfProjectName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paRight.add(tfProjectName);

        add(paRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbProjectName;
    private javax.swing.JPanel paLeft;
    private javax.swing.JPanel paRight;
    private javax.swing.JTextField tfProjectName;
    // End of variables declaration//GEN-END:variables
}
