/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulator.gui;

import general.beans.io_objects.CommandRun;
import general.beans.io_objects.ExplorerLayer;
import general.beans.io_objects.ProjectRun;
import general.beans.io_objects.TestCaseRun;
import general.beans.io_objects.TestGroupRun;
import general.bl.GlobalAccess;
import general.bl.GlobalParamter;
import general.io.Mapper;
import java.io.IOException;
import java.net.Socket;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.json.JSONArray;
import org.json.JSONObject;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import remote.bl.RemoteExecutionManager;
import remote.communication.RemoteClient;
import simulator.bl.CommandExecutionManager;
import simulator.bl.ExecutionManager;
//import simulator.bl.CommandExecutionManager;

/**
 *
 * @author Lukas Krobath
 */
public class TestGUI extends javax.swing.JFrame {

    /**
     * Creates new form TestGUI
     */
    public TestGUI() {

        initComponents();
        setLocationRelativeTo(null);
//        try {
        //        try {
//            List<Path> test = new ArrayList<>();
//            test.add(Paths.get("C:\\Develop\\dstore_Testframework\\dtf-project-suite\\trunk\\__HTL_Vorbereitung\\__NEUE_STRUKTUR__\\projekte\\basisregressionstest\\run"));
//            
//            GlobalParamter.getInstance().setWorkingProjects(Mapper.mapFilesToBeans(Paths.get("C:\\Develop\\dstore_Testframework\\dtf-project-suite\\trunk\\__HTL_Vorbereitung\\__NEUE_STRUKTUR__\\projekte\\")));
//            //CommandExecutionManager.getInstance().setTargets(test);
//            //CommandExecutionManager.getInstance().startSimulation();
//            //System.out.println(GlobalAccess.getInstance().getWorkingProjects().get(0).getTestgroups());
//            /*for (ProjectRun workingProject : GlobalAccess.getInstance().getWorkingProjects()) {
//                System.out.println("Entering " + workingProject.getDescription());
//                for (TestGroupRun testgroup : workingProject.getTestgroups()) {
//                    System.out.println("  Entering " + testgroup.getDescription());
//                    for (TestCaseRun testCase : testgroup.getTestCases()) {
//                        System.out.println("    Entering " + testCase.getDescription());
//                        for (CommandRun command : testCase.getCommands()) {
//                            System.out.println("      " + command.getClassName() + " " + command.getPath());
//                        }
//                    }
//                }
//            }*/
//            List<ExplorerLayer> lay = new ArrayList<>();
//            lay.add(GlobalParamter.getInstance().getWorkingProjects().get(0).getTestgroups().get(1));
//            ExecutionManager.getInstance().setTargets(lay);
//            
//           // ExecutionManager.getInstance().startSimulation();
//        } catch (Exception ex) {
//            Logger.getLogger(TestGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }

//            Socket socket = new Socket("localhost", 7486);
//            
//            //tst.add(new test)
//        } catch (IOException ex) {
//            ex.printStackTrace();
//        } catch (InterruptedException ex) {
//            Logger.getLogger(TestGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remotePanel2 = new remote.gui.RemotePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(remotePanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private remote.gui.RemotePanel remotePanel2;
    // End of variables declaration//GEN-END:variables
}
