/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import recorder.io.IOLoader;
import recorder.io.IOSaver;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxi
 */
public class AuthLimitsDlg extends javax.swing.JDialog {

    /**
     * Creates new form AuthLimitsDlg
     * @param parent
     * @param modal
     */
    public AuthLimitsDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(Paths.get(System.getProperty("user.dir"),
                "src", "res", "img", "logo.png").toString()).getImage());
        this.setLocationRelativeTo(null);
        try {
            List<Double> limits = IOLoader.getLimits();
            tfLimitSSTO.setText(limits.get(0) + "");
            tfLimitZSTO.setText(limits.get(1) + "");
            tfLimitBonabbruch.setText(limits.get(2) + "");
            tfGeschenkkarte.setText(limits.get(3) + "");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Die Konfigurationsdatei hat einen Fehler - bitte geben Sie die Grenzen manuell ein", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfLimitSSTO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfLimitZSTO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfLimitBonabbruch = new javax.swing.JTextField();
        lbGeschenkkarte = new javax.swing.JLabel();
        tfGeschenkkarte = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(952, 405));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 6));

        lbInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbInfo.setText("Bitte die Grenzen für die Autorisierung definieren:");
        jPanel3.add(lbInfo);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 6, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Sofortstorno [€]:");
        jPanel1.add(jLabel1);

        tfLimitSSTO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLimitSSTO.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfLimitSSTO.setText("50");
        jPanel1.add(tfLimitSSTO);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Zeilenstorno [€]:");
        jPanel1.add(jLabel2);

        tfLimitZSTO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLimitZSTO.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfLimitZSTO.setText("50");
        jPanel1.add(tfLimitZSTO);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Bonabbruch [€]:");
        jPanel1.add(jLabel3);

        tfLimitBonabbruch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLimitBonabbruch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfLimitBonabbruch.setText("50");
        jPanel1.add(tfLimitBonabbruch);

        lbGeschenkkarte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGeschenkkarte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbGeschenkkarte.setText("Geschenkkarte [€]:");
        jPanel1.add(lbGeschenkkarte);

        tfGeschenkkarte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfGeschenkkarte.setText("50");
        jPanel1.add(tfGeschenkkarte);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(13, 1, 1, 1));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Okay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOk(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Abbrechen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is executed when the dialog is finished with "OK"
     * @param evt
     */
    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        List<Double> tmp = new ArrayList<>();
        try {
            tmp.add(Double.parseDouble(tfLimitSSTO.getText()));
            tmp.add(Double.parseDouble(tfLimitZSTO.getText()));
            tmp.add(Double.parseDouble(tfLimitBonabbruch.getText()));
            tmp.add(Double.parseDouble(tfGeschenkkarte.getText()));
            IOSaver.saveLimits(tmp);
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "Fehler in den Eingabefeldern! Geben Sie als Kommatrennnzeichen einen Punkt ein.", "Fehler", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Fehler beim Speichern der Datei", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_onOk

    /**
     * Method that is executed when the dialog is finished with "Cancel"
     * Handlermethode, die bei einer negativen Beendigung ausgeführt wird
     * @param evt
     */
    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthLimitsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthLimitsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthLimitsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthLimitsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AuthLimitsDlg dialog = new AuthLimitsDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbGeschenkkarte;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JTextField tfGeschenkkarte;
    private javax.swing.JTextField tfLimitBonabbruch;
    private javax.swing.JTextField tfLimitSSTO;
    private javax.swing.JTextField tfLimitZSTO;
    // End of variables declaration//GEN-END:variables
}
