/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Maxi
 */
public class ELoadingDlg extends javax.swing.JDialog {

    private String status = null;

    /**
     * Creates new form ELoadingDlg
     *
     * @param parent
     * @param modal
     */
    public ELoadingDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(Paths.get(System.getProperty("user.dir"),
                "src", "res", "img", "logo.png").toString()).getImage());
        this.setSize(350, 500);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOption1 = new javax.swing.JButton();
        btOption2 = new javax.swing.JButton();
        btOption3 = new javax.swing.JButton();
        btOption4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 1, 15, 15));

        btOption1.setBackground(new java.awt.Color(255, 255, 255));
        btOption1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOption1.setText("Server offline");
        btOption1.setActionCommand("server_offline");
        btOption1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStatusSelected(evt);
            }
        });
        getContentPane().add(btOption1);

        btOption2.setBackground(new java.awt.Color(255, 255, 255));
        btOption2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOption2.setText("Verkauf NOK");
        btOption2.setActionCommand("verkauf_nok");
        btOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStatusSelected(evt);
            }
        });
        getContentPane().add(btOption2);

        btOption3.setBackground(new java.awt.Color(255, 255, 255));
        btOption3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOption3.setText("Aufladung OK");
        btOption3.setActionCommand("aufladung_ok");
        btOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStatusSelected(evt);
            }
        });
        getContentPane().add(btOption3);

        btOption4.setBackground(new java.awt.Color(255, 255, 255));
        btOption4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOption4.setText("Aufladung NOK");
        btOption4.setActionCommand("aufladung_nok");
        btOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStatusSelected(evt);
            }
        });
        getContentPane().add(btOption4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that saves the selection status
     * @param evt
     */
    private void onStatusSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onStatusSelected
        status = evt.getActionCommand();
        dispose();
    }//GEN-LAST:event_onStatusSelected

    public String getStatus() {
        return status;
    }

    public JButton getBtOption1() {
        return btOption1;
    }

    public JButton getBtOption2() {
        return btOption2;
    }

    public JButton getBtOption3() {
        return btOption3;
    }

    public JButton getBtOption4() {
        return btOption4;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ELoadingDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ELoadingDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ELoadingDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ELoadingDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ELoadingDlg dialog = new ELoadingDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOption1;
    private javax.swing.JButton btOption2;
    private javax.swing.JButton btOption3;
    private javax.swing.JButton btOption4;
    // End of variables declaration//GEN-END:variables
}
