/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import java.nio.file.Paths;
import javax.swing.ImageIcon;

/**
 *
 * @author annalechner
 */
public class ELoadingBonstornoDlg extends javax.swing.JDialog {

    private String status = null;
    
    /**
     * Creates new form ELoadingBonstornoDlg
     * @param parent
     * @param modal
     */
    public ELoadingBonstornoDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(Paths.get(System.getProperty("user.dir"), 
                "src", "res", "img", "logo.png").toString()).getImage());
        setSize(350, 500);
        setTitle("Informationsdialog");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMitStornoOK = new javax.swing.JButton();
        btMitStornoNOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0, 15, 15));

        btMitStornoOK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMitStornoOK.setText("Mit eLoading-Artikel: Storno OK");
        btMitStornoOK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btMitStornoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });
        getContentPane().add(btMitStornoOK);

        btMitStornoNOK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMitStornoNOK.setText("Mit eLoading-Artikel: Storno NOK");
        btMitStornoNOK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btMitStornoNOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });
        getContentPane().add(btMitStornoNOK);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that saves the selected option
     * @param evt 
     */
    private void onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClick
        status = evt.getActionCommand();
        dispose();
    }//GEN-LAST:event_onClick

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ELoadingBonstornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ELoadingBonstornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ELoadingBonstornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ELoadingBonstornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ELoadingBonstornoDlg dialog = new ELoadingBonstornoDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMitStornoNOK;
    private javax.swing.JButton btMitStornoOK;
    // End of variables declaration//GEN-END:variables
}
