/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import java.awt.Dimension;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author annalechner
 */
public class JugendschutzDlg extends javax.swing.JDialog {

    private boolean ok = false;

    /**
     * Erstellt neuen JugendschutzDlg
     *
     * @param parent
     * @param modal
     */
    public JugendschutzDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ZoneId zonedId = ZoneId.of("Europe/Berlin");
        LocalDate today = LocalDate.now(zonedId);
        LocalDate sixteen = today.minusYears(16);
        LocalDate eighteen = today.minusYears(18);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        lbBirthday16.setText(dtf.format(sixteen) + "");
        lbBirthday18.setText(dtf.format(eighteen) + "");
        setTitle("Jugendschutz");
        setSize(new Dimension(500, 400));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paLabels = new javax.swing.JPanel();
        lbAge16 = new javax.swing.JLabel();
        lbBirthday16 = new javax.swing.JLabel();
        lbAge18 = new javax.swing.JLabel();
        lbBirthday18 = new javax.swing.JLabel();
        paButtons = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onClosing(evt);
            }
        });

        paLabels.setLayout(new java.awt.GridLayout(4, 0));

        lbAge16.setBackground(new java.awt.Color(255, 51, 51));
        lbAge16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAge16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAge16.setText("Jugendschutzartikel ab 16 Jahre:");
        lbAge16.setOpaque(true);
        paLabels.add(lbAge16);

        lbBirthday16.setBackground(new java.awt.Color(255, 255, 255));
        lbBirthday16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbBirthday16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBirthday16.setOpaque(true);
        paLabels.add(lbBirthday16);

        lbAge18.setBackground(new java.awt.Color(255, 51, 51));
        lbAge18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAge18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAge18.setText("Jugendschutzartikel ab 18 Jahre:");
        lbAge18.setOpaque(true);
        paLabels.add(lbAge18);

        lbBirthday18.setBackground(new java.awt.Color(255, 255, 255));
        lbBirthday18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbBirthday18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBirthday18.setOpaque(true);
        paLabels.add(lbBirthday18);

        getContentPane().add(paLabels, java.awt.BorderLayout.CENTER);

        paButtons.setPreferredSize(new java.awt.Dimension(400, 50));
        paButtons.setLayout(new java.awt.GridLayout(1, 2, 30, 30));

        btOk.setBackground(new java.awt.Color(255, 255, 255));
        btOk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOk(evt);
            }
        });
        paButtons.add(btOk);

        btCancel.setBackground(new java.awt.Color(255, 255, 255));
        btCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        paButtons.add(btCancel);

        getContentPane().add(paButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is called when the user presses OK
     * @param evt
     */
    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        ok = true;
        dispose();
    }//GEN-LAST:event_onOk

    /**
     * Method that is called when the user presses "Cancel"
     * @param evt
     */
    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        ok = false;
        dispose();
    }//GEN-LAST:event_onCancel

    /**
     * Handlermethode für ein frühzeitiges Schließen des Dialoges
     * @param evt
     */
    private void onClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClosing
        ok = false;
    }//GEN-LAST:event_onClosing

    public boolean isOk() {
        return ok;
    }

    public void setOk(boolean ok) {
        this.ok = ok;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugendschutzDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugendschutzDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugendschutzDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugendschutzDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JugendschutzDlg().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbAge16;
    private javax.swing.JLabel lbAge18;
    private javax.swing.JLabel lbBirthday16;
    private javax.swing.JLabel lbBirthday18;
    private javax.swing.JPanel paButtons;
    private javax.swing.JPanel paLabels;
    // End of variables declaration//GEN-END:variables
}
