/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import recorder.guiOperations.GUIOperations;

/**
 *
 * @author Florian Deutschmann
 */
public class MehrwertdienststornoDlg extends javax.swing.JDialog {

    private static final Font DEFAULT_FONT = new Font("Tahoma", Font.BOLD, 18);
    private JButton btnAccept = new JButton("Bestätigen");
    private boolean ok;
    private boolean pfeiltaste;

    private String displayText = "";

    /**
     * Creates new form MehrwertdienststornoDLG
     *
     * @param parent
     * @param modal
     */
    public MehrwertdienststornoDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnAccept.addActionListener(this::onOk);
        btnAccept.setFont(DEFAULT_FONT);
    }

    public boolean isOk() {
        return ok;
    }

    public boolean isPfeiltaste() {
        return pfeiltaste;
    }

    public String getDisplayText() {
        return displayText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paDynamicContent = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mehrwertdienstartikelstorno");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 50));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        paDynamicContent.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Pfeiltaste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPfeiltaste(evt);
            }
        });
        paDynamicContent.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Touch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTouch(evt);
            }
        });
        paDynamicContent.add(jButton2);

        getContentPane().add(paDynamicContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is called when the user chooses the option "Pfeiltaste"
     *
     * @param evt
     */
    private void onPfeiltaste(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPfeiltaste

        paDynamicContent.removeAll();
        paDynamicContent.setLayout(new GridLayout(3, 1, 0, 10));

        JPanel rbPanel_1 = new JPanel(new GridLayout(1, 2));
        JPanel rbPanel_2 = new JPanel(new GridLayout(1, 2));

        JRadioButton rb_up_1 = new JRadioButton("up");
        JRadioButton rb_up_2 = new JRadioButton("up");
        JRadioButton rb_down_1 = new JRadioButton("down");
        JRadioButton rb_down_2 = new JRadioButton("down");
        rb_up_1.setFont(DEFAULT_FONT);
        rb_up_2.setFont(DEFAULT_FONT);
        rb_down_1.setFont(DEFAULT_FONT);
        rb_down_2.setFont(DEFAULT_FONT);

        rb_up_1.setSelected(true);
        rb_up_2.setSelected(true);

        ButtonGroup bg_1 = new ButtonGroup();
        bg_1.add(rb_up_1);
        bg_1.add(rb_down_1);

        ButtonGroup bg_2 = new ButtonGroup();
        bg_2.add(rb_up_2);
        bg_2.add(rb_down_2);

        rbPanel_1.add(rb_up_1);
        rbPanel_1.add(rb_down_1);
        rbPanel_2.add(rb_up_2);
        rbPanel_2.add(rb_down_2);

        paDynamicContent.add(rbPanel_1);
        paDynamicContent.add(rbPanel_2);
        paDynamicContent.add(btnAccept);

        pfeiltaste = true;

        paDynamicContent.updateUI();
    }//GEN-LAST:event_onPfeiltaste

    /**
     * Method that is called when the user chooses the option "Touch"
     *
     * @param evt
     */
    private void onTouch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTouch
        pfeiltaste = false;
        paDynamicContent.removeAll();
        paDynamicContent.setLayout(new GridLayout(2, 1, 0, 10));

        JTextField tfIndex = new JTextField();
        tfIndex.setToolTipText("Display-Index eingeben");

        tfIndex.setFont(DEFAULT_FONT);
        paDynamicContent.add(tfIndex);
        paDynamicContent.add(btnAccept);
        paDynamicContent.updateUI();
    }//GEN-LAST:event_onTouch

    /**
     * Method that is called when the user presses OK
     *
     * @param evt
     */
    private void onOk(ActionEvent evt) {
        this.ok = true;
        if (pfeiltaste) {
            String part_1 = ((JRadioButton) (((JPanel) (paDynamicContent.getComponent(0))).getComponent(0))).isSelected() ? "up" : "down";
            String part_2 = ((JRadioButton) (((JPanel) (paDynamicContent.getComponent(1))).getComponent(0))).isSelected() ? "up" : "down";
            displayText = String.format("%s,%s", part_1, part_2);
        } else {
            try {
                int tmp_int = Integer.parseInt(((JTextField) (paDynamicContent.getComponent(0))).getText());
                displayText = tmp_int + "";
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(GUIOperations.getMainframe(), "Bitte geben Sie eine valide Zahl ein!");
                return;
            }
        }
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MehrwertdienststornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MehrwertdienststornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MehrwertdienststornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MehrwertdienststornoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MehrwertdienststornoDlg dialog = new MehrwertdienststornoDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel paDynamicContent;
    // End of variables declaration//GEN-END:variables
}
