/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxi
 */
public class OverloadValuesDlg extends javax.swing.JDialog {

    private String id = null;
    private String subId = null;
    private double value;

    /**
     * Creates new form OverloadValuesDlg
     *
     * @param parent
     * @param modal
     * @param subId
     */
    public OverloadValuesDlg(java.awt.Frame parent, boolean modal, boolean subId) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(Paths.get(System.getProperty("user.dir"),
                "src", "res", "img", "logo.png").toString()).getImage());
        this.setLocationRelativeTo(null);
        if (!subId) {
            lbSubId.setEnabled(false);
            tfSubId.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        lbSubId = new javax.swing.JLabel();
        tfSubId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfValue = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 6));

        lbInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbInfo.setText("Bitte die Werte für die nachträgliche Änderung an Bon-Werten eingeben:");
        jPanel3.add(lbInfo);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 6, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1);

        tfId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(tfId);

        lbSubId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSubId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSubId.setText("Sub-ID:");
        jPanel1.add(lbSubId);

        tfSubId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSubId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(tfSubId);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Wert:");
        jPanel1.add(jLabel3);

        tfValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfValue.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(tfValue);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(13, 1, 1, 1));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Okay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOk(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Abbrechen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is called when user presses OK
     * @param evt
     */
    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        id = tfId.getText();
        subId = tfSubId.getText();
        try {
            value = Double.parseDouble(tfValue.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Bitte für den Wert eine Zahl "
                    + "in der Form 12.34 eingeben!");
            return;
        }
        dispose();
    }//GEN-LAST:event_onOk

    /**
     * Method that is called when the user presses "Cancel"
     * @param evt
     */
    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    public String getId() {
        return id;
    }

    public String getSubId() {
        return subId;
    }

    public double getValue() {
        return value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbSubId;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfSubId;
    private javax.swing.JTextField tfValue;
    // End of variables declaration//GEN-END:variables
}
