/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recorder.gui.dlg;

import javax.swing.JOptionPane;

/**
 *
 * @author annalechner
 */
public class WarenruecknahmePreisDlg extends javax.swing.JDialog {

    private double preis;

    /**
     * Creates new form WarenruecknahmePreisDlg
     * @param parent
     * @param modal
     * @param preisRegu
     */
    public WarenruecknahmePreisDlg(java.awt.Frame parent, boolean modal, double preisRegu) {
        super(parent, modal);
        initComponents();
        tfPreisRegu.setText(String.format("%.2f", preisRegu));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPreis = new javax.swing.ButtonGroup();
        paMain = new javax.swing.JPanel();
        rbPreisRegu = new javax.swing.JRadioButton();
        tfPreisRegu = new javax.swing.JTextField();
        rbPreisNeu = new javax.swing.JRadioButton();
        tfPreisNeu = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onClose(evt);
            }
        });

        paMain.setLayout(new java.awt.GridLayout(2, 0, 2, 10));

        bgPreis.add(rbPreisRegu);
        rbPreisRegu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbPreisRegu.setSelected(true);
        rbPreisRegu.setText("Regulärer Preis:");
        paMain.add(rbPreisRegu);

        tfPreisRegu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfPreisRegu.setEnabled(false);
        paMain.add(tfPreisRegu);

        bgPreis.add(rbPreisNeu);
        rbPreisNeu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbPreisNeu.setText("Neuer Preis:");
        paMain.add(rbPreisNeu);

        tfPreisNeu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paMain.add(tfPreisNeu);

        getContentPane().add(paMain, java.awt.BorderLayout.CENTER);

        btOk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOk.setText("Übernehmen");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOk(evt);
            }
        });
        getContentPane().add(btOk, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that saves the selected price
     * @param evt 
     */
    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        try {
            if (rbPreisRegu.isSelected()) {
                String preisRegu = tfPreisRegu.getText().replaceAll(",", ".");
                preis = Double.parseDouble(preisRegu);
            } else if (rbPreisNeu.isSelected()) {
                String preisNeu = tfPreisNeu.getText().replaceAll(",", ".");
                preis = Double.parseDouble(preisNeu);
            }
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Bitte einen validen Preis (mit . oder ,) eingeben!");
        }
    }//GEN-LAST:event_onOk

    /**
     * Method that handles the closing event
     * @param evt 
     */
    private void onClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClose
        preis = Double.parseDouble(tfPreisRegu.getText().replaceAll(",", "."));
        dispose();
    }//GEN-LAST:event_onClose

    public double getPreis() {
        return preis;
    }

    public void setPreis(double preis) {
        this.preis = preis;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarenruecknahmePreisDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarenruecknahmePreisDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarenruecknahmePreisDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarenruecknahmePreisDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                WarenruecknahmePreisDlg dialog = new WarenruecknahmePreisDlg(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPreis;
    private javax.swing.JButton btOk;
    private javax.swing.JPanel paMain;
    private javax.swing.JRadioButton rbPreisNeu;
    private javax.swing.JRadioButton rbPreisRegu;
    private javax.swing.JTextField tfPreisNeu;
    private javax.swing.JTextField tfPreisRegu;
    // End of variables declaration//GEN-END:variables
}
