/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analyzer.gui;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import settings.io.Loader;

/**
 * Class to display an initialization dialog so that the user could
 * enter relevant information for the diffing process
 * in case of a manual start
 * 
 * @author Maximilian Strohmaier
 */
public class AnalyzerInitDlg extends javax.swing.JDialog {

    private Path refPath = null;
    private Path ergPath = null;
    private boolean ok = false;
    
    /**
     * Creates new form AnalyzerInitDlg
     */
    public AnalyzerInitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(700, 250);
        setLocationRelativeTo(null);
        setTitle("Bitte die Pfade für die Analyse auswählen");
    }
    
    /**
     * Method to let the user choose a directory and return the respective file object
     * 
     * @return  chosen directory as a file object, null if nothing was selected
     */
    private File chooseDir()
    {
        JFileChooser fc = new JFileChooser();
        try {
             File projectDir = new File(Loader.getSpecificParameter(false).get("projectPath"));
             fc.setCurrentDirectory(projectDir);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            return fc.getSelectedFile();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paCenter = new javax.swing.JPanel();
        lbRefPath = new javax.swing.JLabel();
        paRefPathSelection = new javax.swing.JPanel();
        tfRefPath = new javax.swing.JTextField();
        btChooseRefPath = new javax.swing.JButton();
        lbErgPath = new javax.swing.JLabel();
        paErgPathSelection = new javax.swing.JPanel();
        tfErgPath = new javax.swing.JTextField();
        btChooseErgPath = new javax.swing.JButton();
        paSouth = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 8));

        paCenter.setLayout(new java.awt.GridLayout(2, 2, 8, 8));

        lbRefPath.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbRefPath.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbRefPath.setText("Referenz:");
        lbRefPath.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        paCenter.add(lbRefPath);

        paRefPathSelection.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 1, 1, 12));
        paRefPathSelection.setLayout(new java.awt.BorderLayout(8, 0));

        tfRefPath.setEditable(false);
        tfRefPath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paRefPathSelection.add(tfRefPath, java.awt.BorderLayout.CENTER);

        btChooseRefPath.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        btChooseRefPath.setText("+");
        btChooseRefPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddRefPath(evt);
            }
        });
        paRefPathSelection.add(btChooseRefPath, java.awt.BorderLayout.EAST);

        paCenter.add(paRefPathSelection);

        lbErgPath.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbErgPath.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbErgPath.setText("Ergebnis:");
        lbErgPath.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 1, 1));
        paCenter.add(lbErgPath);

        paErgPathSelection.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 12));
        paErgPathSelection.setLayout(new java.awt.BorderLayout(8, 0));

        tfErgPath.setEditable(false);
        tfErgPath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paErgPathSelection.add(tfErgPath, java.awt.BorderLayout.CENTER);

        btChooseErgPath.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        btChooseErgPath.setText("+");
        btChooseErgPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddErgPath(evt);
            }
        });
        paErgPathSelection.add(btChooseErgPath, java.awt.BorderLayout.EAST);

        paCenter.add(paErgPathSelection);

        getContentPane().add(paCenter, java.awt.BorderLayout.CENTER);

        paSouth.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 12, 12));
        paSouth.setLayout(new java.awt.GridLayout(1, 2, 8, 0));

        btOk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOk.setText("Übernehmen");
        btOk.setPreferredSize(new java.awt.Dimension(151, 15));
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOk(evt);
            }
        });
        paSouth.add(btOk);

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCancel.setText("Abbrechen");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        paSouth.add(btCancel);

        getContentPane().add(paSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Method called when clicking on the button to add a new reference path
     * 
     * @param evt 
     */
    private void onAddRefPath(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddRefPath
        // TODO add your handling code here:
        File chosenFile = chooseDir();
        if(chosenFile != null)
        {
            tfRefPath.setText(chosenFile.getName());
            tfRefPath.setToolTipText(chosenFile.getAbsolutePath());
            refPath = chosenFile.toPath();
        }
    }//GEN-LAST:event_onAddRefPath

    /**
     * Method called when clicking on the button to add a new result path
     * 
     * @param evt 
     */
    private void onAddErgPath(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddErgPath
        // TODO add your handling code here:
        File chosenFile = chooseDir();
        if(chosenFile != null)
        {
            tfErgPath.setText(chosenFile.getName());
            tfErgPath.setToolTipText(chosenFile.getAbsolutePath());
            ergPath = chosenFile.toPath();
        }
    }//GEN-LAST:event_onAddErgPath
    
    /**
     * Method called when clicking on cancel button
     * 
     * @param evt 
     */
    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        // TODO add your handling code here:
        ok = false;
        dispose();
    }//GEN-LAST:event_onCancel

    /**
     * Method called when clicking on ok button
     * 
     * @param evt 
     */
    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        // TODO add your handling code here:
        if(refPath == null || ergPath == null)
        {
            JOptionPane.showMessageDialog(null, "Bitte alle Felder ausfüllen!");
            return;
        }
        ok = true;
        dispose();
    }//GEN-LAST:event_onOk

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btChooseErgPath;
    private javax.swing.JButton btChooseRefPath;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbErgPath;
    private javax.swing.JLabel lbRefPath;
    private javax.swing.JPanel paCenter;
    private javax.swing.JPanel paErgPathSelection;
    private javax.swing.JPanel paRefPathSelection;
    private javax.swing.JPanel paSouth;
    private javax.swing.JTextField tfErgPath;
    private javax.swing.JTextField tfRefPath;
    // End of variables declaration//GEN-END:variables

    public Path getRefPath() {
        return refPath;
    }

    public Path getErgPath() {
        return ergPath;
    }

    public boolean isOk() {
        return ok;
    }
}
